biodb/biodb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from biodb import views
from django.conf import settings


urlpatterns = [
    # Examples:
    # url(r'^$', 'biodb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.RedirectView.as_view(), name="welcome_page"),
    url(r'^projects/', include("projects.urls")),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

biodb/robjects/urls.py
from django.conf.urls import url

from robjects.views import NameCreateView
from robjects.views import ExportExcelView
from robjects.views import RobjectCreateView
from robjects.views import RobjectDeleteView
from robjects.views import RobjectDetailView
from robjects.views import RobjectEditView
from robjects.views import RobjectHistoryView
from robjects.views import RobjectListView
from robjects.views import RobjectPDFeView
from robjects.views import RobjectSamplesList
from robjects.views import SearchRobjectsView
from robjects.views import TagCreateView

app_name = 'robjects'
urlpatterns = [
    url(r"^search/$",
        SearchRobjectsView.as_view(), name="search_robjects"),
    url(r"^$", RobjectListView.as_view(), name="robjects_list"),
    url(r"^create/$", RobjectCreateView.as_view(), name="robject_create"),
    url(r'^(?P<robject_id>[0-9]+)/edit/$',
        RobjectEditView.as_view(), name="robject_edit"),
    url(r"^delete/$", RobjectDeleteView.as_view(), name="robject_delete"),
    url(r"^excel-raport/$", ExportExcelView.as_view(), name="raport_excel"),
    url(r"^(?P<robject_id>\d+)/history/$", RobjectHistoryView.as_view(),
        name="robject_history"),
    url(r"^PDF-raport/$", RobjectPDFeView.as_view(), name="pdf_raport"),
    url(r"^names-create/$", NameCreateView.as_view(), name="names_create"),
    url(r"^tags-create/$", TagCreateView.as_view(), name="tags_create"),
    url(r'^(?P<robject_id>[0-9]+)/samples/$',
        RobjectSamplesList.as_view(), name='robject_samples'),
    url(r'^(?P<robject_id>[0-9]+)/details/$',
        RobjectDetailView.as_view(), name='robject_details'),

]

biodb/robjects/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from projects.models import RelatedModelsCustomManager
from simple_history.models import HistoricalRecords
from django.core.urlresolvers import reverse
# Create your models here.


class Robject(models.Model):
    project = models.ForeignKey(to=Project, null=True, blank=True)
    author = models.ForeignKey(
        to=User, blank=True, null=True, related_name="robjects_in_which_user_is_author")
    name = models.CharField(max_length=100, null=True)
    create_by = models.ForeignKey(
        to=User, related_name="robjects_created_by_user", null=True, blank=True)
    create_date = models.DateTimeField(
        null=True, blank=True, auto_now_add=True)
    modify_by = models.ForeignKey(to=User, null=True, blank=True)
    modify_date = models.DateTimeField(null=True, auto_now=True)
    tags = models.ManyToManyField("Tag", related_name="robjects", blank=True)
    names = models.ManyToManyField("Name", related_name="robjects", blank=True)
    notes = RichTextField(blank=True)
    ref_seq = RichTextField(blank=True)
    mod_seq = RichTextField(blank=True)
    description = RichTextField(blank=True)
    bibliography = RichTextField(blank=True)
    ref_commercial = RichTextField(blank=True)
    ref_clinical = RichTextField(blank=True)
    ligand = models.CharField(max_length=100, blank=True)
    receptor = models.CharField(max_length=100, blank=True)
    history = HistoricalRecords()

    def __str__(self):
        return "Robject " + str(self.id)

    class Meta:
        unique_together = ("name", "project")

    @staticmethod
    def get_fields(instance, fields=None):
        """
        Return dictionary with object fields: {field.verbose_name: field class}
        Attrs:
        """
        if not fields:
            fields = []
        fields_dict = {field.verbose_name: getattr(
            instance, field.name) for field in instance._meta.get_fields() if field.name in fields}
        return sorted(fields_dict.items())

    def get_general_fields(self):
        '''
            Return fields : id, create_date, create_by, modify_date, modify_by, author
        '''
        fields = ["id", "create_date", "create_by",
                  "modify_date", "modify_by", "author"]
        return self.get_fields(self, fields)

    def get_detail_fields(self):
        '''
            Return fields: ligand, receptor, ref_seq, mod_seq,
            description, bibliography, ref_commercial, ref_clinical, notes
        '''
        fields = ["ligand", "receptor", "ref_seq", "mod_seq", "description",
                  "bibliography", "ref_commercial", "ref_clinical", "notes"]
        return self.get_fields(self, fields)

    def get_fields_names(self, exclude=None, relation=False):
        """This method return set of model fields.

        All fields are received automatically from model.
        By default relational fields are not included.

        Args:
            exclude (:obj:`list` or `set`): list of names of fields to exclude.
            relation (bool): True include relational fields. Defaults: False.

        Returns:
            :obj:`set`: Set containing model fields names.
        """
        # create set from input list | remove duplicates the same time
        if not exclude:
            excludes = set()
        else:
            excludes = set(exclude)
        # get set from model dict keys
        if relation:
            fields = set(f.name for f in self._meta.get_fields())
        else:
            fields = set(f.name for f in self._meta.get_fields()
                         if not (f.is_relation or f.one_to_one or
                                 (f.many_to_one and f.related_model)))
        # return difference set
        return fields.difference(excludes)

    @property
    def _history_user(self):
        return self.modify_by

    @_history_user.setter
    def _history_user(self, value):
        self.modify_by = value


class Name(models.Model):
    name = models.CharField(max_length=100, unique=True)
    objects = RelatedModelsCustomManager()

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    project = models.ForeignKey(to=Project, related_name="tags", null=True)
    objects = RelatedModelsCustomManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("projects:tag_list", kwargs={"project_name": self.project.name})

biodb/samples/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from robjects.models import Robject
# Create your models here.


class Sample(models.Model):
    """
        Robjects sample object.
    """
    UNASSIGNED = 1
    REQUESTED = 2
    MOL_MOD = 3
    # IN_PROGRESS
    PREP = 5
    OPTIMAILIZATION = 6
    PRODUCTION = 7
    QA_CONTROL = 8
    COMPLETED = 9
    CANCELED = 10
    ON_HOLD = 11
    LIBRARY = 12

    STATUS_CHOICES = ((UNASSIGNED, 'Unassigned'),
                      (REQUESTED, 'Requested'),
                      (MOL_MOD, 'Molecular Modelling'),
                      (PREP, 'Preperation'),
                      (OPTIMAILIZATION, 'Optimalization'),
                      (PRODUCTION, 'Production'),
                      (QA_CONTROL, 'Quality COntrol'),
                      (COMPLETED, 'Completed'),
                      (CANCELED, 'Canceled'),
                      (ON_HOLD, 'ON_HOLD'),
                      (LIBRARY, 'Library'))

    code = models.CharField(max_length=100, blank=True)
    robject = models.ForeignKey(to=Robject, null=True)
    owner = models.ForeignKey(
        to=User, null=True, related_name="sample_in_which_user_is_owner")
    create_date = models.DateTimeField(null=True, auto_now_add=True)
    modify_date = models.DateTimeField(null=True, auto_now=True)
    modify_by = models.ForeignKey(to=User, null=True)
    notes = RichTextField(null=True, blank=True)
    form = models.CharField(max_length=100, blank=True)
    source = models.CharField(max_length=100, blank=True)
    status = models.IntegerField(default=1, choices=STATUS_CHOICES)

    def __str__(self):
        return "Sample " + str(self.id)

    @staticmethod
    def get_fields(instance, fields=None):
        """
        Return dictionary with object fields:
            {field.verbose_name: field class, ...}

        Attrs:
        """
        if not fields:
            fields = []
        fields_dict = {field.verbose_name: getattr(
            instance, field.name) for field in instance._meta.get_fields()
                       if field.name in fields}
        return sorted(fields_dict.items())

biodb/robjects/templates/robjects/names_create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" name="" value="Submit">
    </form>
  </body>
</html>

biodb/robjects/templates/robjects/robject_confirm_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p class="message">
      {% if robjects %}

        Are you sure you want to delete following robject(s):
        {% for robject in robjects %}
          {{ robject.name }}{% if object|length > forloop.counter %},{% endif %}
        {% endfor %}
        ?

        <form class="" action="" method="post">
          {% csrf_token %}
          <input class="confirm-delete" type="submit" value="Confirm">
        </form>
      {% else %}

        You haven't choose any elements to delete. Please, step back and select elements from table.

      {% endif %}
    </p>
    <a class="get-back-link"
      href="{% url 'projects:robjects:robjects_list' project_name=request.resolver_match.kwargs.project_name %}">
        Back to robjects list.
    </a>
  </body>
</html>

biodb/robjects/templates/robjects/robject_create.html
{% extends "biodb/base.html" %}
{% load static %}
{% block content %}
  <form class="" action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button name="button">Submit</button>
    {{ form.media }}
  </form>
{% endblock %}

biodb/robjects/templates/robjects/robject_details.html
{% extends "biodb/base.html" %}
{% block content %}
{% load render_table from django_tables2 %}
{% load static %}

<h1>
  {{ object.name }}
</h1>
<ul class="general-fields">
    {% for gfield_name, gfield_value in object.get_general_fields %}
        <li>{{ gfield_name }}: {{ gfield_value }}</li>
    {% endfor %}
</ul>
<ul class="details-fields">
    {% for dfield_name, dfield_value in object.get_detail_fields %}
        <li>{{ dfield_name }}: {{ dfield_value }}</li>
    {% endfor %}
</ul>

<a class="link_back" href="{% url 'projects:robjects:robjects_list' object.project.name %}">Back to robject table</a>

{% endblock %}

biodb/robjects/templates/robjects/robject_history.html
{% extends "biodb/base.html" %}
{% load static %}
{% block extra_head %}
<!-- extra here -->
{% endblock %}

{% block content %}
<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Type</th>
      <th>Changed by</th>
      <th>Modyfication date</th>
      <th>Changes</th>
    </tr>
  </thead>
  <tbody>
    {% for version in versions %}
      <tr>
        <td>{{ version.version_id }}</td>
        <td>{{ version.modify_type }}</td>
        <td>{{ version.modify_by }}</td>
        <td>{{ version.modify_date }}</td>
        <td>
          {% with diffobjects=version.get_diff_objects %}
            {% if  diffobjects %}
              {% for difffield in diffobjects %}
                <div class="field-diff">
                  {{ difffield.field }}
                  <div class="new">{{ difffield.new_value }}</div>
                  <div class="old">{{ difffield.old_value }}</div>
                </div>
              {% endfor %}
            {% else %}
              <div class="field-diff">&mdash;</div>
            {% endif %}
          {% endwith %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

biodb/robjects/templates/robjects/robject_raport_pdf.html
<html>
 <head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
  <style>
      @page {
        margin: 3cm 3cm;
        @top-center {
            content: "   ";
            width: 100%;
            vertical-align: bottom;
            border-bottom: .5pt solid;
            margin-bottom: 1.2cm;
            color: gray;
        }
        @top-right{
            color: gray;
            font-size: 70%;
            content: "Confidential";
        }
        @top-left{
            color: gray;
            font-size: 70%;
            content: "Studynumber";
        }
        @bottom-right {
            font-size: 70%;
            content: "Page " counter(page) " of " counter(pages);
            color: gray;
        }
        @bottom-left {
            font-size: 70%;
            content: "Created: {{ create_date }} by {{ request.user | capfirst}}";
            color: gray;
        }
    }
    @media print {
        #detail_table {page-break-after: always;}
    }
    }
  </style>
</head>

{% if robjects %}
  {% for robject in robjects %}
<h1>Raport</h1>
<div class="names">
  <h2>{{ robject.name }}</h2>
</div>

  <table id="general_table">
    <caption>General Table </caption>
    {% for field, value in robject.get_general_fields %}
    <tr>
      <th>{{ field }}:</th>
      <td nowrap>{{ value }}</td>
    </tr>
    {% endfor %}
  </table>
  <table id="detail_table">
    <caption>Detail Table </caption>
    {% for field, value in robject.get_detail_fields %}
    <tr>
      <th>{{ field }}: </th>
      <td nowrap>{{ value }}</td>
    </tr>
    {% endfor %}
  </table>

{% endfor %}

{% else %}
  No objects were selected
{% endif  %}
  </body>
 </html>

biodb/robjects/templates/robjects/robjects_list.html
{% extends "biodb/base.html" %} {% load static %} {% block extra_head %}
<link rel="stylesheet" href="{% static 'projects/robject_list.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="{% static 'projects/select_all.js' %}">

</script>
{% endblock %} {% block content %}

<!-- Search form -->
<form id="search_form" action="/projects/{{ project_name }}/robjects/search/">
  <input type="text" name="query" id="search_input">
  <button id="search_button">Search</button>
</form>
<!-- End search form -->

<!-- Links section -->
<div class="links">
  Links:
  <ul>
    <li>
      <a
      href="{% url 'projects:samples:sample_list' project_name=request.resolver_match.kwargs.project_name %}">
        Sample table
      </a>
    </li>
    <li>
      <a href="{% url 'projects:robjects:robject_create' project_name=request.resolver_match.kwargs.project_name %}">
        Create research object.
      </a>
    </li>
  </ul>
</div>
<!-- End links section -->

<!-- Actions section -->
<div class="actions">
  Actions:
  <ul>
    <li>
      <input type="submit" value="Delete" class="delete-button"
      form="robjects-form"
      formaction="{% url 'projects:robjects:robject_delete' project_name=request.resolver_match.kwargs.project_name %}">
    </li>
    <li>
      <input type="submit" value='Excel' class="excel-button"
      formaction="/projects/{{ project_name }}/robjects/excel-raport/"
      form="robjects-form"
      >
    </li>
    <li>
      <input type="submit" value="PDF" class="pdf-button"
      formaction="{% url 'projects:robjects:pdf_raport' project_name=request.resolver_match.kwargs.project_name %}"
      form="robjects-form">
    </li>
  </ul>
</div>
<!-- End actions section -->

<!-- Robject table -->
<form id="robjects-form">
  <table id="robjects_table">
    <tr id="header_row">
      <th><input type="checkbox" class="select-all"></th>
      <th>id</th>
      <th>name</th>
      <th>author</th>
      <th>create by</th>
      <th>create date</th>
      <th>modify by</th>
    </tr>
    {% for robject in robject_list %}
      <tr class="row {{ robject.name }}">
        <td>
          <input
          type="checkbox"
          class="robject checkbox"
          name="{{ robject.name }}"
          value="{{ robject.id }}">
        </td>
        <td>{{ robject.id }}</td>
        <td><a href="{% url 'projects:robjects:robject_details' robject.project.name robject.pk%}">{{ robject.name }}</a></td>
        <td>{{ robject.author }}</td>
        <td>{{ robject.create_by }}</td>
        <td>{{ robject.create_date }}</td>
        <td>{{ robject.modify_by }}</td>
      </tr>
      {% endfor %}
    </table>
</form>
<!-- End robject table -->

<style>
  .links, .actions {
    margin: 20px 0;
  }
  #export_excel{
     border:0;
     background:none;
     /*And other css to remove the default button property */
}
</style>{% endblock %}

biodb/robjects/templates/robjects/tags_create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" name="" value="Submit">
    </form>
  </body>
</html>